# Pinhole Camera Model Practice Questions

## Question 1: Perspective Projection

A 3D point in the camera coordinate system is given by `p_c = [10, 5, 20]`. 
The camera has a focal length `f` of 50mm. 
Calculate the position of the projection of this point on the image plane in meters.

In [13]:
# Your code here
import numpy as np
p_c = [10, 5, 20]
f = 0.05
u_c = f*(p_c[0]/p_c[2])
v_c = f*(p_c[1]/p_c[2])
p_m = (u_c, v_c)
print(p_m)

(0.025, 0.0125)


---

## Question 2: Conversion to Pixels

Given the projected point from Question 1, convert its coordinates from meters to pixels. 
Assume the following intrinsic parameters: 
- `s_x` = 800 pixels/meter
- `s_y` = 800 pixels/meter
- `o_x` = 320 pixels
- `o_y` = 240 pixels
What are the pixel coordinates `(u^I, v^I)`?

In [15]:
# Your code here
s_x = 800
s_y = 800
o_x = 320
o_y = 240
u_I = s_x*p_m[0] + o_x
v_I = s_y*p_m[1] + o_y
print (u_I, v_I)

340.0 250.0


---

## Question 3: Intrinsic Matrix

Construct the intrinsic calibration matrix `K` using the parameters from Question 2, assuming no skew (`s_θ = 0`).

In [19]:
# Your code here
s_θ = 0
K = np.array([[s_x*f, s_θ*f, o_x],[0, s_y*f, o_y], [0, 0, 1]])
print(K)

[[ 40.   0. 320.]
 [  0.  40. 240.]
 [  0.   0.   1.]]


---

## Question 4: Point Projection with Known Pose

A point in the world frame is given by `p_w = [2, 3, 50]`. The camera's pose `T_w^c` is given by an identity rotation matrix and a translation vector `t_w^c = [0, 0, 10]`. [cite_start]Using the intrinsic matrix `K` from Question 3, calculate the pixel coordinates of the projected point. [cite: 14, 16, 17]

In [53]:
# Your code here
p_w = np.array([2, 3, 50, 1])
t_w_c = np.array([0, 0, 10])
t_w_c_reshape = t_w_c.reshape(3,1)
R = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
ext_cal = np.hstack((R, t_w_c_reshape))
P = K @ ext_cal
P_p_w = P @ p_w 
u_I2 = P_p_w[0]/P_p_w[2]
v_I2 = P_p_w[1]/P_p_w[2]
print(u_I1,v_I2)

321.3333333333333 242.0


---

## Question 5: Radial Distortion

A point is projected on the image plane at `(u_distort^I, v_distort^I) = (400, 350)` including radial distortion. Given distortion coefficients `a1 = 0.0001` and `a2 = 0.0000002` and the principal point `(o_x, o_y) = (320, 240)`, calculate the corrected pixel coordinates `(u^I, v^I)`.

In [61]:
# Your code here
(u_distort_I, v_distort_I) = (400, 350)
a1 = 0.0001
a2 = 0.0000002
(o_x, o_y) = (320, 240)
r_squared = (u_distort_I)**2 + (v_distort_I)**2
u_I3 = (1 + a1*r_squared + a2*r_squared**2)*(u_distort_I - o_x) + o_x
v_I3 = (1 + a1*r_squared + a2*r_squared**2)*(v_distort_I - o_y) + o_y
print(u_I3, v_I3)

1279560.0 1759195.0
